DATASET_NAME: 'birds'
DATA_DIR: '/userhome/shuchenweng/datasets/birds'
MODEL_DIR: '/userhome/shuchenweng/modelsets/birds'
PRETRAINED_DIR: '/userhome/shuchenweng/pretrained/birds'
CKPT: '/userhome/shuchenweng/pretrained/birds/netG_epoch_113_15.62.pth'
GPU_ID: 0
WORKERS: 0


TREE:
    BRANCH_NUM: 3


TRAIN:
    FLAG: True
    BATCH_SIZE: 127  # 22
    MAX_EPOCH: 1000
    SNAPSHOT_INTERVAL: 1
    DISCRIMINATOR_LR: 0.0002
    GENERATOR_LR: 0.0002


TEST:
    BATCH_SIZE: 16

GAN:
    DF_DIM: 64
    GF_DIM: 32
    Z_DIM: 100
    R_NUM: 2

TEXT:
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
